server:
  port: 8080
#=================================阿里巴巴连接池==================
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://49.235.238.184:3306/Video?useUnicode=true&characterEncoding=utf-8
    username: root
    password: liujunwei520
    driver-class-name: com.mysql.jdbc.Driver
#=================================redis配置开始==================
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    #  # Redis服务器地址
    host: falsecloud.cn
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Liujunwei123
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1024
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
    timeout: 10000
    # redis配置结束
    block-when-exhausted: true
# =================================mybatis配置开始==================
mybatis-plus:
  configuration:
    #数据库下划线-->驼峰
    map-underscore-to-camel-case: true
    #打印sql，方便调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapperxml/*.xml
# =================================文件上传路径配置==================
upfile:
  #服务器：/opt/video/fileImage   开发环境配置：D:/video/fileImage
  fileSpace: /opt/video/fileImage
# FFMPEG所在目录
FFMPEG: ./opt/ffmpeg/bin/ffmpeg
#每页分页数
Page_Size: 5